### ISSUE TITLE
Correctly parse DataCite XML for formats and sizes

### ISSUE THREAD

**Issue by mfenner** [datacite/bolognese#103] opened 2020-12-16 08:06 UTC
Correctly handle `xs:string` attribute, e.g. for `10.4225/13/511C71F8612C3`.

**Comment by richardhallett** [comment] 2021-03-23 09:55
I can't reproduce this, I added a spec test for this.
https://github.com/datacite/bolognese/commit/a7335c19540745d48bfa388318d78be2e5014830

Closing but reopen if further example.

**Closed by richardhallett** 2021-03-23 09:55 UTC
Labels: bug
