### ISSUE TITLE
Correctly parse xs:string

### ISSUE THREAD

**Issue by mfenner** [datacite/bolognese#51] opened 2018-12-30 11:50 UTC
Example DOI: 10.4225/13/511C71F8612C3

**Comment by richardhallett** [comment] 2019-10-04 09:23
Closing as unable to reproduce a parsing problem, the example DOI does have errors but this is due to schema version 2.2 and the metadata not being correct, not due parding xs:string.

**Closed by richardhallett** 2019-10-04 09:23 UTC
Labels: DOI Fabrica, bug
