### ISSUE TITLE
the Bolognese gem doesn't properly handle the optional language attribute.

### ISSUE THREAD

**Issue by kjgarza** [datacite/bolognese#8] opened 2017-05-23 11:11 UTC
the Bolognese gem doesn't properly handle the optional language attribute.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1qk5)

**Comment by mfenner** [comment] 2017-05-31 11:09
Duplicate of #3.

**Closed by mfenner** 2017-05-31 11:09 UTC
Labels: bug, duplicate
