### ISSUE TITLE
Undefined method `dig' in read_crossref

### ISSUE THREAD

**Issue by flange-ipb** [datacite/bolognese#20] opened 2017-12-29 10:06 UTC
Try to use bolognese with the DOI 10.1111/nph.14619:
```
$ bolognese https://doi.org/10.1111/nph.14619
/var/lib/gems/2.3.0/gems/bolognese-0.9.65/lib/bolognese/readers/crossref_reader.rb:156:in `read_crossref': undefined method `dig' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/bolognese-0.9.65/lib/bolognese/metadata.rb:113:in `initialize'
        from /var/lib/gems/2.3.0/gems/bolognese-0.9.65/lib/bolognese/cli.rb:32:in `new'
        from /var/lib/gems/2.3.0/gems/bolognese-0.9.65/lib/bolognese/cli.rb:32:in `convert'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/bolognese-0.9.65/bin/bolognese:6:in `<top (required)>'
        from /usr/local/bin/bolognese:23:in `load'
        from /usr/local/bin/bolognese:23:in `<main>'
```

**Comment by mfenner** [comment] 2017-12-29 10:11
The error is probably caused by Ruby version < 2.3, as `dig` was added then: https://www.tiagoamaro.com.br/2016/08/27/ruby-2-3-dig/

I will add a requirement for Ruby 2.3, as this method is heavily used in bolognese and a big time saver.

**Comment by mfenner** [comment] 2017-12-29 10:39
@flange-ipb I have created a new version `v.0.9.66` that should be available via RubyGems in a few minutes. But that version doesn't really help you until you upgrade to Ruby 2.3 or 2.4, assuming that this is the underlying issue.

**Comment by flange-ipb** [comment] 2017-12-29 10:44
I'm using ruby version 2.3.1pl12.
It seems journal_issue is simply null, because meta.dig("crossref", "journal", "journal_issue") in crossref_reader.rb:112 is either never called or it returns null. Also check CrossRef's metadata for 10.1111/nph.14619 - it has no issue field.

**Comment by mfenner** [comment] 2017-12-29 10:52
Thanks, will create a test for that particular DOI to reproduce and fix this particular parsing issue.

**Comment by mfenner** [comment] 2017-12-29 13:45
@flange-ipb this should been fixed in the newest version that I just released, `v.0.9.67`. And as you said, the missing issue field wasn't handled properly.

**Closed by mfenner** 2017-12-29 13:45 UTC
Labels: bug
